import { HttpStatus } from "@nestjs/common";
import { ProductErrorCode } from "src/modules/products/domain/errors/enums/product-error-code.enum";

export const productDomainErrorToHttpStatusMap: Record<ProductErrorCode, HttpStatus> =
{
  // 400 Bad Request - Validation errors
  PRODUCT_INVALID_PRODUCT_ID: HttpStatus.BAD_REQUEST,
  PRODUCT_INVALID_SKU: HttpStatus.BAD_REQUEST,
  PRODUCT_INVALID_PRICE: HttpStatus.BAD_REQUEST,
  PRODUCT_INVALID_NAME: HttpStatus.BAD_REQUEST,
  PRODUCT_INVALID_ATTRIBUTES: HttpStatus.BAD_REQUEST,
  PRODUCT_INVALID_STATUS: HttpStatus.BAD_REQUEST,
  PRODUCT_STATE_CONFLICT: HttpStatus.BAD_REQUEST,
  PRODUCT_INVALID_STATUS_TRANSITION: HttpStatus.BAD_REQUEST,
  PRODUCT_PRICE_CANNOT_BE_NEGATIVE: HttpStatus.BAD_REQUEST,
  PRODUCT_PRICE_CHANGE_TOO_LARGE: HttpStatus.BAD_REQUEST,
  PRODUCT_INVALID_TILE_SIZE: HttpStatus.BAD_REQUEST,
  PRODUCT_INVALID_PRODUCT_SIZE: HttpStatus.BAD_REQUEST,
  PRODUCT_INVALID_DIMENSION_UNIT: HttpStatus.BAD_REQUEST,
  PRODUCT_INVALID_GRADE: HttpStatus.BAD_REQUEST,
  PRODUCT_INVALID_FINISHING: HttpStatus.BAD_REQUEST,
  PRODUCT_INVALID_APPLICATION_AREA: HttpStatus.BAD_REQUEST,

  // 409 Conflict - Business rule conflicts
  PRODUCT_IS_DISCONTINUED: HttpStatus.CONFLICT,
  PRODUCT_IS_DELETED: HttpStatus.CONFLICT,
  PRODUCT_IS_INACTIVE: HttpStatus.CONFLICT,
  PRODUCT_OUT_OF_STOCK: HttpStatus.CONFLICT,
  PRODUCT_CANNOT_DELETE_PRODUCT: HttpStatus.CONFLICT,
  PRODUCT_CANNOT_UPDATE_PRODUCT: HttpStatus.CONFLICT,
};
