export const PaymentErrorCode = {
  INVALID_PAYMENT_ID: 'PAYMENT_INVALID_PAYMENT_ID',
  INVALID_PROVIDER_REF: 'PAYMENT_INVALID_PROVIDER_REF',
  INVALID_PAYMENT_STATUS: 'PAYMENT_INVALID_PAYMENT_STATUS',
  INVALID_PAYMENT_STATUS_TRANSITION: 'PAYMENT_INVALID_STATUS_TRANSITION',
  INVALID_PAYMENT_AMOUNT: 'PAYMENT_INVALID_AMOUNT',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_ALREADY_EXISTS: 'PAYMENT_ALREADY_EXISTS',
  PAYMENT_STATE_CONFLICT: 'PAYMENT_STATE_CONFLICT',
  PAYMENT_PROVIDER_ERROR: 'PAYMENT_PROVIDER_ERROR',
  DUPLICATE_PROVIDER_REF: 'PAYMENT_DUPLICATE_PROVIDER_REF',
} as const;

export type PaymentErrorCode =
  (typeof PaymentErrorCode)[keyof typeof PaymentErrorCode];
