export const AuthErrorCode = {
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  PASSWORD_TOO_WEAK: 'AUTH_PASSWORD_TOO_WEAK',
  INVALID_PROVIDER: 'AUTH_INVALID_PROVIDER',
  INVALID_AUTH_STATE: 'AUTH_INVALID_AUTH_STATE',
  EMAIL_ALREADY_IN_USE: 'AUTH_EMAIL_ALREADY_IN_USE',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  CANNOT_VERIFY_EMAIL: 'AUTH_CANNOT_VERIFY_EMAIL',
  CANNOT_UNVERIFY_EMAIL: 'AUTH_CANNOT_UNVERIFY_EMAIL',
} as const;

export type AuthErrorCode = typeof AuthErrorCode[keyof typeof AuthErrorCode];