import { AddressLabel, AuthProvider, Gender, UserStatus, Role } from "src/generated/prisma/enums";
export type CreateUserParams = {
  firstName?: string;
  lastName?: string;
  password?: string;
  gender: Gender;
  email: string;
  emailVerified?: boolean;
  provider?: AuthProvider;
  providerId?: string;
  role?: Role;
  status?: UserStatus;
  dateOfBirth?: Date;
  phoneNumber?: string;
  phoneVerified?: boolean;
  avatarUrl?: string;
  address?: {
    label: AddressLabel;
    recipient: string;
    phone: string;
    street: string;
    city: string;
    province: string;
    postalCode: string;
    country?: string;
    latitude?: number;
    longitude?: number;
    isDefault?: boolean;
  };
};