export const InventoryErrorCode = {
  // Validation errors
  INVALID_INVENTORY_ID: 'INVENTORY_INVALID_INVENTORY_ID',
  INVALID_STOCK_QUANTITY: 'INVENTORY_INVALID_STOCK_QUANTITY',
  STATE_CONFLICT: 'INVENTORY_STATE_CONFLICT',

  // Business rule errors
  INVENTORY_NOT_FOUND: 'INVENTORY_NOT_FOUND',
  INVENTORY_ALREADY_EXISTS: 'INVENTORY_ALREADY_EXISTS',
  INSUFFICIENT_STOCK: 'INVENTORY_INSUFFICIENT_STOCK',
  INVALID_RESERVATION: 'INVENTORY_INVALID_RESERVATION',

  // Operation errors
  CANNOT_UPDATE_INVENTORY: 'INVENTORY_CANNOT_UPDATE_INVENTORY',
  CANNOT_RELEASE_MORE_THAN_RESERVED: 'INVENTORY_CANNOT_RELEASE_MORE_THAN_RESERVED',
} as const;

export type InventoryErrorCode =
  (typeof InventoryErrorCode)[keyof typeof InventoryErrorCode];
