export const DiscountErrorCode = {
  // Validation errors
  INVALID_DISCOUNT_ID: 'DISCOUNT_INVALID_DISCOUNT_ID',
  INVALID_DISCOUNT_CODE: 'DISCOUNT_INVALID_DISCOUNT_CODE',
  INVALID_DISCOUNT_VALUE: 'DISCOUNT_INVALID_DISCOUNT_VALUE',
  INVALID_DISCOUNT_STATUS: 'DISCOUNT_INVALID_DISCOUNT_STATUS',
  INVALID_DISCOUNT_PERIOD: 'DISCOUNT_INVALID_DISCOUNT_PERIOD',
  STATE_CONFLICT: 'DISCOUNT_STATE_CONFLICT',

  // Business rule errors
  DISCOUNT_NOT_FOUND: 'DISCOUNT_NOT_FOUND',
  DISCOUNT_ALREADY_EXISTS: 'DISCOUNT_ALREADY_EXISTS',
  DISCOUNT_CODE_ALREADY_EXISTS: 'DISCOUNT_CODE_ALREADY_EXISTS',
  DISCOUNT_EXPIRED: 'DISCOUNT_EXPIRED',
  DISCOUNT_INACTIVE: 'DISCOUNT_INACTIVE',
  DISCOUNT_USAGE_LIMIT_REACHED: 'DISCOUNT_USAGE_LIMIT_REACHED',
  DISCOUNT_NOT_APPLICABLE: 'DISCOUNT_NOT_APPLICABLE',
  INVALID_STATUS_TRANSITION: 'DISCOUNT_INVALID_STATUS_TRANSITION',
  DISCOUNT_NOT_YET_ACTIVE: 'DISCOUNT_NOT_YET_ACTIVE',

  // Operation errors
  CANNOT_UPDATE_DISCOUNT: 'DISCOUNT_CANNOT_UPDATE_DISCOUNT',
  CANNOT_DELETE_DISCOUNT: 'DISCOUNT_CANNOT_DELETE_DISCOUNT',
} as const;

export type DiscountErrorCode =
  (typeof DiscountErrorCode)[keyof typeof DiscountErrorCode];
