export const ProductErrorCode = {
  // Validation errors
  INVALID_SKU: 'PRODUCT_INVALID_SKU',
  INVALID_PRICE: 'PRODUCT_INVALID_PRICE',
  INVALID_NAME: 'PRODUCT_INVALID_NAME',
  INVALID_ATTRIBUTES: 'PRODUCT_INVALID_ATTRIBUTES',
  INVALID_STATUS: 'PRODUCT_INVALID_STATUS',

  // Business rule errors  
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_ALREADY_EXISTS: 'PRODUCT_ALREADY_EXISTS',
  SKU_ALREADY_EXISTS: 'PRODUCT_SKU_ALREADY_EXISTS',
  INVALID_STATUS_TRANSITION: 'PRODUCT_INVALID_STATUS_TRANSITION',
  PRODUCT_IS_DISCONTINUED: 'PRODUCT_IS_DISCONTINUED',
  PRODUCT_IS_INACTIVE: 'PRODUCT_IS_INACTIVE',
  PRODUCT_OUT_OF_STOCK: 'PRODUCT_OUT_OF_STOCK',
  
  // Price errors
  PRICE_CANNOT_BE_NEGATIVE: 'PRODUCT_PRICE_CANNOT_BE_NEGATIVE',
  PRICE_CHANGE_TOO_LARGE: 'PRODUCT_PRICE_CHANGE_TOO_LARGE',
  
  // Attribute errors
  INVALID_TILE_SIZE: 'PRODUCT_INVALID_TILE_SIZE',
  INVALID_GRADE: 'PRODUCT_INVALID_GRADE',
  INVALID_FINISHING: 'PRODUCT_INVALID_FINISHING',
  INVALID_APPLICATION_AREA: 'PRODUCT_INVALID_APPLICATION_AREA',
  
  // Operation errors
  CANNOT_DELETE_PRODUCT: 'PRODUCT_CANNOT_DELETE_PRODUCT',
  CANNOT_UPDATE_PRODUCT: 'PRODUCT_CANNOT_UPDATE_PRODUCT',
} as const;

export type ProductErrorCode =
  (typeof ProductErrorCode)[keyof typeof ProductErrorCode];
