export const OrderErrorCode = {
  // Validation errors
  INVALID_ORDER_ID: 'ORDER_INVALID_ORDER_ID',
  INVALID_ORDER_ITEM_ID: 'ORDER_INVALID_ORDER_ITEM_ID',
  INVALID_ORDER_NUMBER: 'ORDER_INVALID_ORDER_NUMBER',
  INVALID_ORDER_STATUS: 'ORDER_INVALID_ORDER_STATUS',
  INVALID_MONEY: 'ORDER_INVALID_MONEY',
  STATE_CONFLICT: 'ORDER_STATE_CONFLICT',

  // Business rule errors
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_ALREADY_EXISTS: 'ORDER_ALREADY_EXISTS',
  INVALID_STATUS_TRANSITION: 'ORDER_INVALID_STATUS_TRANSITION',
  ORDER_IS_EMPTY: 'ORDER_IS_EMPTY',
  ORDER_CANNOT_BE_CANCELLED: 'ORDER_CANNOT_BE_CANCELLED',
  ORDER_CANNOT_BE_MODIFIED: 'ORDER_CANNOT_BE_MODIFIED',

  // Operation errors
  CANNOT_ADD_ITEM: 'ORDER_CANNOT_ADD_ITEM',
  CANNOT_REMOVE_ITEM: 'ORDER_CANNOT_REMOVE_ITEM',
} as const;

export type OrderErrorCode =
  (typeof OrderErrorCode)[keyof typeof OrderErrorCode];
