export const EmailErrorCode = {
  // ✉️ Email Format
  EMAIL_FORMAT_INVALID: "EMAIL_FORMAT_INVALID",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  EMAIL_ALREADY_VERIFIED: "EMAIL_ALREADY_VERIFIED",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  EMAIL_VERIFICATION_STATE_MISMATCH: "EMAIL_VERIFICATION_STATE_MISMATCH",

} as const;

export type EmailErrorCode = typeof EmailErrorCode[keyof typeof EmailErrorCode];