export const UserErrorCode = {
  // 🔍 Not Found
  USER_NOT_FOUND: "USER_NOT_FOUND",

  // 🧍‍♂️ Existence / Uniqueness
  USER_EMAIL_ALREADY_EXISTS: "USER_EMAIL_ALREADY_EXISTS",
  USER_USERNAME_ALREADY_EXISTS: "USER_USERNAME_ALREADY_EXISTS",

  // 🚫 State / Status
  USER_INACTIVE: "USER_INACTIVE",
  USER_SUSPENDED: "USER_SUSPENDED",
  USER_DELETED: "USER_DELETED",
  USER_BANNED: "USER_BANNED",

  // 🔐 Authentication & Authorization
  USER_UNAUTHORIZED: "USER_UNAUTHORIZED",
  USER_FORBIDDEN: "USER_FORBIDDEN",
  USER_INSUFFICIENT_PERMISSIONS: "USER_INSUFFICIENT_PERMISSIONS",

  // 🔑 Password & Credentials
  USER_INVALID_CREDENTIALS: "USER_INVALID_CREDENTIALS",
  USER_PASSWORD_INVALID: "USER_PASSWORD_INVALID",
  USER_PASSWORD_MISMATCH: "USER_PASSWORD_MISMATCH",
  USER_PASSWORD_EXPIRED: "USER_PASSWORD_EXPIRED",
  USER_PASSWORD_TOO_WEAK: "USER_PASSWORD_TOO_WEAK",

  // ✉️ Email & Verification
  USER_EMAIL_INVALID: "USER_EMAIL_INVALID",
  USER_EMAIL_NOT_VERIFIED: "USER_EMAIL_NOT_VERIFIED",
  USER_EMAIL_ALREADY_VERIFIED: "USER_EMAIL_ALREADY_VERIFIED",

  // 🎫 Token & Session
  USER_TOKEN_INVALID: "USER_TOKEN_INVALID",
  USER_TOKEN_EXPIRED: "USER_TOKEN_EXPIRED",
  USER_SESSION_EXPIRED: "USER_SESSION_EXPIRED",

  // 🔁 Operation Constraints
  USER_CANNOT_BE_UPDATED: "USER_CANNOT_BE_UPDATED",
  USER_CANNOT_BE_DELETED: "USER_CANNOT_BE_DELETED",
  USER_CANNOT_SELF_DELETE: "USER_CANNOT_SELF_DELETE",
  USER_CANNOT_CHANGE_OWN_ROLE: "USER_CANNOT_CHANGE_OWN_ROLE",

  // 📍 Profile & Data
  USER_PROFILE_INCOMPLETE: "USER_PROFILE_INCOMPLETE",
  USER_AVATAR_UPLOAD_FAILED: "USER_AVATAR_UPLOAD_FAILED",

  // 🔗 OAuth & External
  USER_OAUTH_LINK_FAILED: "USER_OAUTH_LINK_FAILED",
  USER_OAUTH_ALREADY_LINKED: "USER_OAUTH_ALREADY_LINKED",
  USER_PROVIDER_NOT_LINKED: "USER_PROVIDER_NOT_LINKED",
  USER_INVALID_PROVIDER: "USER_INVALID_PROVIDER",
} as const;

export type UserErrorCode = typeof UserErrorCode[keyof typeof UserErrorCode];